name: 'Skoreyko & Sons'
favicon: null
layout_spectrum: 0.393931076861918
typography_spectrum: 0.51169
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d1d3d5'
    - '#161616'
    - '#bb8635'
    - '#3c4242'
    - '#73736f'
  brandStrength: 0.687659173971042
  lightness: 0.48581288009881973
  saturation: 0.3313400123734027
  rhythmicContrast: 0.0017600131686776876
purpose: []
